context:
    leftheader: "Lewy nagłówek"
    rightheader: "Prawy nagłówek!!"
    buttonlink: "https://www.sealcode.org/"
    button_params: {
		text: "Dowiedz się więcej",
		link: buttonlink,
		color: "purple",
    }
