import { resolve } from "path";

export = {
	context: {
		title: "the team",
		members: [
			{
				image_path: resolve(__dirname, "placeholder.png"),
				name: "Agata Slater",
				role: "CEO &amp; co-founder",
				area_of_expertise: "business",
				key_skill: "interdisciplinarity",
				opinion: "“Passion Personified”",
				proud_of: "her dog not chewing other dogs to death",
				heard_saying: "“There is this research I read recently”",
				email: "agata.slater@evolver.team",
				telephone: "970-244-0851",
				facebook: "https://www.facebook.com/agata.daleszynska",
				linkedin:
					"https://www.linkedin.com/in/agata-slater-phd-0a3716a0/",
				gender: "female",
			},
			{
				image_path: resolve(__dirname, "placeholder.png"),
				name: "Jagoda Szulia",
				role: "COO &amp; co-founder",
				area_of_expertise: "storytelling",
				key_skill: "executive coaching",
				opinion: "“She&rsquo;s probably still sleeping”",
				proud_of: "her book collection",
				heard_saying: "“I have an idea”",
				email: "jagoda.szulia@evolver.team",
				telephone: "970-244-0851",
				facebook: "https://www.facebook.com/dzordzu.mckinsey",
				linkedin: "https://www.linkedin.com/in/jagodaszulia/",
				gender: "female",
			},
			{
				image_path: resolve(__dirname, "placeholder.png"),
				name: "Remigiusz Antczak",
				role: "CIO &amp; co-founder",
				area_of_expertise: "project management",
				key_skill: "bringing order to chaos",
				opinion: "“He&rsquo;ll figure it out”",
				proud_of: "Evolvers",
				heard_saying: "“We need to do it asap”",
				email: "remi@evolver.team",
				telephone: "970-114-0851",
				facebook: "https://www.facebook.com/Remigius.Antczak",
				linkedin: "https://www.linkedin.com/in/remigius-antczak/",
				gender: "male",
			},
			{
				image_path: resolve(__dirname, "placeholder.png"),
				name: "Konrad Mroczko",
				role: "CXO &amp; co-founder",
				area_of_expertise: "design",
				key_skill: "playing devil&rsquo;s advocate",
				opinion: "“Deep diving? Go see Konrad”",
				proud_of: "his hippie shirt",
				heard_saying: "“I just want to do it right”",
				email: "konrad.mroczko@evolver.team",
				telephone: "970-114-0851",
				facebook: "https://www.facebook.com/knrdm",
				linkedin: "linkedin.com",
				gender: "male",
			},
		],
	},
};
