context:
    splash_data:
        header_top: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,"
        header_bottom: "suspendisse semper lacinia commodo"
        description: "Vivamus non nisl at felis vestibulum porta. Sed et facilisis elit. Vivamus at ligula iaculis, fringilla lorem in, volutpat mauris. Nam blandit tempor lorem eu sollicitudin. Mauris sit amet turpis nunc. Mauris consequat ornare eros, et euismod dui porttitor sit amet. Aliquam nec vehicula odio. Mauris dapibus odio dolor, eget iaculis nibh molestie eu. Morbi nunc sapien, faucibus a odio id, condimentum volutpat ante"
